# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Machine Learning
email: liushouda@qq.com
description: > # this means to ignore newlines until "baseurl:"
  关注计算机视觉，自然语言处理，语音识别。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vsooda
github_username:  vsooda

# Build settings
#markdown: kramdown
#markdown: rdiscount #对mou的支持较好
markdown: redcarpet
#permalink: pretty 
